ERROR - 2024-02-25 00:51:39 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 00:51:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(\'Rogelio\', 2, 1)')
 3 APPPATH/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 00:55:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 00:55:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(\'Rogelio\', 2, 1)')
 3 APPPATH/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 00:56:02 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 00:56:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(\'Rogelio\', 2, 1)')
 3 APPPATH/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 00:57:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 00:57:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(\'Roger\', 2, 1)')
 3 APPPATH/Controllers/Cine.php(30): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 01:14:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 01:14:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(peliculaId, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 01:28:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 01:28:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(1, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 01:29:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 01:29:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(1, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 01:33:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 01:33:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(1, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 02:02:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 02:02:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(1, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 02:02:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 02:02:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(1, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-25 02:05:13 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "Cine/cartelera.php"
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Cine/cartelera.php')
 2 SYSTEMPATH/Common.php(1178): CodeIgniter\View\View->render('Cine/cartelera', [], true)
 3 APPPATH/Controllers/Cine.php(12): view('Cine/cartelera')
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->cartelera()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-25 02:05:16 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "Cine/cartelera.php"
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Cine/cartelera.php')
 2 SYSTEMPATH/Common.php(1178): CodeIgniter\View\View->render('Cine/cartelera', [], true)
 3 APPPATH/Controllers/Cine.php(12): view('Cine/cartelera')
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->cartelera()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-25 02:05:17 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "Cine/cartelera.php"
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Cine/cartelera.php')
 2 SYSTEMPATH/Common.php(1178): CodeIgniter\View\View->render('Cine/cartelera', [], true)
 3 APPPATH/Controllers/Cine.php(12): view('Cine/cartelera')
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->cartelera()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-25 02:05:20 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "Cine/cartelera.php"
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Cine/cartelera.php')
 2 SYSTEMPATH/Common.php(1178): CodeIgniter\View\View->render('Cine/cartelera', [], true)
 3 APPPATH/Controllers/Cine.php(12): view('Cine/cartelera')
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->cartelera()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-25 02:05:27 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "Cine/cartelera.php"
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Cine/cartelera.php')
 2 SYSTEMPATH/Common.php(1178): CodeIgniter\View\View->render('Cine/cartelera', [], true)
 3 APPPATH/Controllers/Cine.php(12): view('Cine/cartelera')
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->cartelera()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-25 02:05:31 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "Cine/cartelera.php"
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Cine/cartelera.php')
 2 SYSTEMPATH/Common.php(1178): CodeIgniter\View\View->render('Cine/cartelera', [], true)
 3 APPPATH/Controllers/Cine.php(12): view('Cine/cartelera')
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->cartelera()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-25 02:05:35 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "Cine/cartelera.php"
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Cine/cartelera.php')
 2 SYSTEMPATH/Common.php(1178): CodeIgniter\View\View->render('Cine/cartelera', [], true)
 3 APPPATH/Controllers/Cine.php(12): view('Cine/cartelera')
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->cartelera()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-25 02:05:35 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "Cine/cartelera.php"
in SYSTEMPATH/Exceptions/FrameworkException.php on line 39.
 1 SYSTEMPATH/View/View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Cine/cartelera.php')
 2 SYSTEMPATH/Common.php(1178): CodeIgniter\View\View->render('Cine/cartelera', [], true)
 3 APPPATH/Controllers/Cine.php(12): view('Cine/cartelera')
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->cartelera()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 02:06:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 02:06:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(1, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 03:04:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 03:04:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(1, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 03:05:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 03:05:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(1, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 03:10:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 03:10:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(1, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-25 03:10:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#4 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#7 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVe...')
#3 /Applications/MAMP/htdocs/Proyecto/app/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', Array)
#4 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
#5 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
#6 /Applications/MAMP/htdocs/Proyecto/vendor/codeigniter4/framework/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Applications/MAMP/htdocs/Proyecto/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-02-25 03:10:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Model.php(868): CodeIgniter\Database\BaseConnection->query('CALL InsertarVenta(1, 2, 1)')
 3 APPPATH/Controllers/Cine.php(29): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\Cine->insertarVenta()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cine))
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
